os: osx
sudo: true
addons:
  homebrew:
    brewfile: true
before_install:
  - sed -i '' -E '/exiftool|epic-games|ffmpeg|google-chrome|mounty|phantomjs|virtualbox|whatsapp/d' Brewfile
script:
  - brew update && brew bundle
